import React from "react";

const sizeClasses = {
  txtInterRegular20: "font-inter font-normal",
  txtCairoSemiBold16: "font-cairo font-semibold",
  txtPoppinsRegular26: "font-normal font-poppins",
  txtPoppinsRegular16Bluegray700: "font-normal font-poppins",
  txtPoppinsRegular28: "font-normal font-poppins",
  txtPoppinsSemiBold16: "font-poppins font-semibold",
  txtInterBold64: "font-bold font-inter",
  txtPoppinsSemiBold32WhiteA700: "font-poppins font-semibold",
  txtPoppinsSemiBold12: "font-poppins font-semibold",
  txtInterRegular23Green80002: "font-inter font-normal",
  txtPoppinsBold44Orange600: "font-bold font-poppins",
  txtInterRegular23: "font-inter font-normal",
  txtInterRegular24: "font-inter font-normal",
  txtPoppinsSemiBold18: "font-poppins font-semibold",
  txtPoppinsMedium15Black90001: "font-medium font-poppins",
  txtPoppinsBold44Black900: "font-bold font-poppins",
  txtPoppinsMedium18Orange600: "font-medium font-poppins",
  txtPoppinsBold84: "font-bold font-poppins",
  txtInterRegular20Lime900: "font-inter font-normal",
  txtPoppinsRegular14: "font-normal font-poppins",
  txtPoppinsRegular15: "font-normal font-poppins",
  txtPoppinsSemiBold24Black900: "font-poppins font-semibold",
  txtPoppinsRegular16: "font-normal font-poppins",
  txtPoppinsSemiBold24: "font-poppins font-semibold",
  txtPoppinsRegular24: "font-normal font-poppins",
  txtPoppinsRegular13Black90001: "font-normal font-poppins",
  txtPoppinsSemiBold20: "font-poppins font-semibold",
  txtPoppinsRegular20: "font-normal font-poppins",
  txtPoppinsSemiBold20Black90001: "font-poppins font-semibold",
  txtBarlowSemiBold32: "font-barlow font-semibold",
  txtBarlowBold46: "font-barlow font-bold",
  txtPoppinsRegular12Gray90002: "font-normal font-poppins",
  txtPoppinsBold54: "font-bold font-poppins",
  txtBarlowMedium18Gray50004: "font-barlow font-medium",
  txtBarlowRegular14Gray40002: "font-barlow font-normal",
  txtPoppinsBold56: "font-bold font-poppins",
  txtPoppinsRegular11: "font-normal font-poppins",
  txtPoppinsSemiBold36: "font-poppins font-semibold",
  txtInterBold40: "font-bold font-inter",
  txtPoppinsRegular12: "font-normal font-poppins",
  txtPoppinsRegular13: "font-normal font-poppins",
  txtPoppinsMedium54: "font-medium font-poppins",
  txtPoppinsSemiBold32: "font-poppins font-semibold",
  txtPoppinsBold60: "font-bold font-poppins",
  txtBarlowMedium14: "font-barlow font-medium",
  txtPoppinsRegular15Black90087: "font-normal font-poppins",
  txtBarlowMedium15: "font-barlow font-medium",
  txtInterRegular23Green90002: "font-inter font-normal",
  txtBarlowMedium18: "font-barlow font-medium",
  txtInterRegular23Green90003: "font-inter font-normal",
  txtPoppinsBold64: "font-bold font-poppins",
  txtPoppinsSemiBold40: "font-poppins font-semibold",
  txtPoppinsSemiBold16Black90087: "font-poppins font-semibold",
  txtPoppinsSemiBold20WhiteA700: "font-poppins font-semibold",
  txtBarlowMedium12: "font-barlow font-medium",
  txtBarlowRegular12Bluegray80001: "font-barlow font-normal",
  txtPoppinsSemiBold32Bluegray900: "font-poppins font-semibold",
  txtCairoBold16: "font-bold font-cairo",
  txtCairoBold18: "font-bold font-cairo",
  txtBarlowRegular16Bluegray800: "font-barlow font-normal",
  txtPoppinsMedium40: "font-medium font-poppins",
  txtPoppinsRegular15Lime300: "font-normal font-poppins",
  txtPoppinsSemiBold20Teal800: "font-poppins font-semibold",
  txtBarlowBold24: "font-barlow font-bold",
  txtInterMedium24: "font-inter font-medium",
  txtInterBold26: "font-bold font-inter",
  txtPoppinsBold30: "font-bold font-poppins",
  txtBarlowRegular12Gray50004: "font-barlow font-normal",
  txtPoppinsBold32: "font-bold font-poppins",
  txtInterMedium24Black900: "font-inter font-medium",
  txtInterBold24: "font-bold font-inter",
  txtInterBold20: "font-bold font-inter",
  txtPoppinsSemiBold54: "font-poppins font-semibold",
  txtBarlowRegular16Gray40002: "font-barlow font-normal",
  txtPoppinsBold18WhiteA700: "font-bold font-poppins",
  txtPoppinsBold14Black900: "font-bold font-poppins",
  txtPoppinsBold24Lightgreen900: "font-bold font-poppins",
  txtPoppinsBold44: "font-bold font-poppins",
  txtPoppinsBold24Bluegray900: "font-bold font-poppins",
  txtPoppinsRegular12Black900: "font-normal font-poppins",
  txtPoppinsMedium24: "font-medium font-poppins",
  txtPoppinsBold26Green900: "font-bold font-poppins",
  txtPoppinsSemiBold64: "font-poppins font-semibold",
  txtPoppinsMedium20: "font-medium font-poppins",
  txtPoppinsBold18Black900: "font-bold font-poppins",
  txtPoppinsRegular15WhiteA700: "font-normal font-poppins",
  txtPoppinsBold26WhiteA700: "font-bold font-poppins",
  txtPoppinsMedium28: "font-medium font-poppins",
  txtPoppinsRegular16Black90001: "font-normal font-poppins",
  txtPoppinsBold16: "font-bold font-poppins",
  txtPoppinsBold18: "font-bold font-poppins",
  txtPoppinsBold32WhiteA700: "font-bold font-poppins",
  txtPoppinsSemiBold24WhiteA700: "font-poppins font-semibold",
  txtBarlowMedium18Bluegray80001: "font-barlow font-medium",
  txtBarlowMedium15Gray50004: "font-barlow font-medium",
  txtPoppinsBold14: "font-bold font-poppins",
  txtPoppinsMedium14: "font-medium font-poppins",
  txtManropeSemiBold18: "font-manrope font-semibold",
  txtPoppinsRegular24Gray90001: "font-normal font-poppins",
  txtPoppinsSemiBold16Black900: "font-poppins font-semibold",
  txtPoppinsBold32Black90001: "font-bold font-poppins",
  txtBarlowSemiBold20: "font-barlow font-semibold",
  txtPoppinsMedium18: "font-medium font-poppins",
  txtPoppinsMedium15: "font-medium font-poppins",
  txtPoppinsMedium16: "font-medium font-poppins",
  txtPoppinsBold32Green800dd: "font-bold font-poppins",
  txtPoppinsBold26: "font-bold font-poppins",
  txtBarlowRegular16: "font-barlow font-normal",
  txtPoppinsBold22Gray900: "font-bold font-poppins",
  txtBarlowBold18: "font-barlow font-bold",
  txtPoppinsBold20: "font-bold font-poppins",
  txtPoppinsBold21: "font-bold font-poppins",
  txtPoppinsSemiBold18Black90090: "font-poppins font-semibold",
  txtPoppinsBold22: "font-bold font-poppins",
  txtPoppinsBold24: "font-bold font-poppins",
  txtBarlowSemiBold18: "font-barlow font-semibold",
  txtBarlowRegular12: "font-barlow font-normal",
  txtPoppinsBold24Lightgreen90001: "font-bold font-poppins",
  txtBarlowRegular14: "font-barlow font-normal",
};

const Text = ({ children, className = "", size, as, ...restProps }) => {
  const Component = as || "p";

  return (
    <Component
      className={`text-left ${className} ${size && sizeClasses[size]}`}
      {...restProps}
    >
      {children}
    </Component>
  );
};

export { Text };
